#!/bin/zsh
aws cloudfront create-invalidation \
  --id file://scripts/aws:cloudfront/distribution-id \
  --invalidation-batch \"Paths={Quantity=1,Items=[\"/index.html\"]},CallerReference=`uuidgen`\"",
